### PR TITLE
add symfony 6 support

### PR DESCRIPTION
**Pull request by robinlehrmann**
Upgrades to symfony 6

### CODE REVIEW

**Comment by robinlehrmann** [comment]
belongs to https://github.com/patchlevel/event-sourcing/issues/120

**Comment by DavidBadura** [comment]
Hey @robinlehrmann, thanks for the contribution. Maybe you should pick this ticket https://github.com/patchlevel/event-sourcing/issues/134 before, so we don't need to support 7.4 anymore :)

**Comment by robinlehrmann** [comment]
@DavidBadura Good point! I will do that 👍

**Review by DavidBadura — APPROVED** [review]

**Review by DanielBadura — APPROVED** [review]

**Comment by DavidBadura** [comment]
thanks @robinlehrmann

**Pull request merged**
